# encoding: utf-8
telefonia = Category.create(:name => 'Telefonia', :parent_category => Category.create(:name => 'Eletronicos'))
celulares = Category.create(:name => 'Celulares', :parent_category => telefonia)
fixos = Category.create(:name => 'Fixos', :parent_category => telefonia)
games = Category.create(:name => 'Games')
ps3 = Category.create(:name => 'PS3', :parent_category => games)
xbox = Category.create(:name => 'XBox', :parent_category => games)
Product.create(:name => 'Galaxy S4', :description => 'A mais nova geração de celulares Android da Samsung', :category => celulares, :price => 2299.0)
Product.create(:name => 'Apple iPhone 4', :description => 'Apple iPhone 4 8GB Branco Desbloqueado', :category => celulares,  :price => 1399.0)
Product.create(:name => 'Telefone Elgin', :description => 'Viva voz, agenda e 2 canais', :category => fixos, :price => 119.0)
Product.create(:name => 'Last of Us', :description => 'O melhor jogo já feito para PS3', :category => ps3,  :price => 149.0)
Product.create(:name => 'Halo 4', :description => 'Clássico do XBox', :category =>  xbox, :price => 99.90)